name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
    # manual trigger

env:
  BUILD_TYPE: Release
  BUILD_CC: clang
  BUILD_CXX: clang++

jobs:
  build:
    runs-on: ubuntu-latest
    container: locietta/loia-dev-base:antlr4

    steps:
    - uses: actions/checkout@v2
    - name: Configure CMake
      run: |
        cmake -B ${{github.workspace}}/build -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}}\
         -DCMAKE_EXPORT_COMPILE_COMMANDS=TRUE -DCMAKE_C_COMPILER=${{env.BUILD_CC}} -DCMAKE_CXX_COMPILER=${{env.BUILD_CXX}}\
         -G Ninja
    - name: Build with CMake
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} --target all

    - name: Upload compiler binary
      uses: actions/upload-artifact@v3
      with:
        name: tinycc
        path: build/tinycc
